table device_analysis
	lineageTag: c9195916-8512-4ef7-ac68-b77ff92b02f8

	column device_type
		dataType: string
		lineageTag: 01074f9a-216d-4a3f-92ad-e90327b38edd
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 0531e7e1-3bd3-4224-ab86-d46adcaa8731
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column purchases
		dataType: int64
		formatString: 0
		lineageTag: 6bdfd824-14fb-4329-b8ac-8ff95e4b583b
		summarizeBy: sum
		sourceColumn: purchases

		annotation SummarizationSetBy = Automatic

	column conversion_rate
		dataType: double
		lineageTag: 85d35343-5b0c-4795-bdaf-2934e7b216ec
		summarizeBy: sum
		sourceColumn: conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition device_analysis = m
		mode: import
		source =
				let
				    源 = Csv.Document(File.Contents("D:\D30360\Documents\ecommerce_funnel_analysis\powerbi\data\device_analysis.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"device_type", type text}, {"sessions", Int64.Type}, {"purchases", Int64.Type}, {"conversion_rate", type number}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

