table funnel_overview
	lineageTag: df763b0f-d44b-4481-a4f7-d00d496df405

	column 漏斗阶段
		dataType: string
		lineageTag: 290ef541-c3a9-4810-b5d3-a134a7443e78
		summarizeBy: none
		sourceColumn: 漏斗阶段
		sortByColumn: 漏斗排序

		annotation SummarizationSetBy = Automatic

	column 到达会话数
		dataType: int64
		formatString: 0
		lineageTag: 1b34318f-4ad2-48f0-93d1-dac6a40bc8b8
		summarizeBy: sum
		sourceColumn: 到达会话数

		annotation SummarizationSetBy = Automatic

	column 购买会话数
		dataType: int64
		formatString: 0
		lineageTag: fa7d5c75-341a-4374-af6c-459bac258c1f
		summarizeBy: sum
		sourceColumn: 购买会话数

		annotation SummarizationSetBy = Automatic

	column 转化率(%)
		dataType: double
		lineageTag: 0eca113d-d45c-41ad-979f-bde959355dbb
		summarizeBy: sum
		sourceColumn: 转化率(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 整体到达率(%)
		dataType: double
		lineageTag: 0533f74f-89a6-46d6-b9b3-da2577cfbe0b
		summarizeBy: sum
		sourceColumn: 整体到达率(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 漏斗排序
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: 漏斗排序

		annotation SummarizationSetBy = Automatic

	partition funnel_overview = m
		mode: import
		source =
				let
				    源 = Csv.Document(File.Contents("D:\D30360\Documents\ecommerce_funnel_analysis\powerbi\data\funnel_overview.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"漏斗阶段", type text}, {"到达会话数", Int64.Type}, {"购买会话数", Int64.Type}, {"转化率(%)", type number}, {"整体到达率(%)", type number}}),
				    添加排序 = Table.AddColumn(更改的类型, "漏斗排序", each if [漏斗阶段] = "首页" then 1 else if [漏斗阶段] = "列表页" then 2 else if [漏斗阶段] = "详情页" then 3 else if [漏斗阶段] = "购物车" then 4 else if [漏斗阶段] = "结算页" then 5 else 99, Int64.Type)
				in
				    添加排序

	annotation PBI_ResultType = Table

