table country_analysis
	lineageTag: 8d3be23e-0ad2-405a-9018-2df1152e4cd7

	column Country
		dataType: string
		lineageTag: d9053a93-5c81-413e-b54e-d80d7f7f2dca
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 9fbe0e4c-5bbf-483c-a0f2-28efe4a354e4
		summarizeBy: none
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: int64
		formatString: 0
		lineageTag: c2c024d8-a284-432e-8e1e-73f518f46b58
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column conversion_rate
		dataType: double
		lineageTag: 16161a85-e408-4d59-b6fe-01120db9a2a1
		summarizeBy: none
		sourceColumn: conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition country_analysis = m
		mode: import
		source =
				let
				    源 = Csv.Document(File.Contents("D:\D30360\Documents\ecommerce_funnel_analysis\powerbi\data\country_analysis.csv"),[Delimiter=",", Columns=4, Encoding=936, QuoteStyle=QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"Country", type text}, {"sessions", Int64.Type}, {"converted", Int64.Type}, {"conversion_rate", type number}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

