table device_analysis
	lineageTag: a44fe7f4-c385-4d8c-8fbd-ee8fc369e5ae

	column DeviceType
		dataType: string
		lineageTag: eeddfccf-6a49-40d5-8f27-9b6f28751844
		summarizeBy: none
		sourceColumn: DeviceType

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 2fb1ed4f-5e8e-4a9b-bb86-3696dc559e22
		summarizeBy: none
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: int64
		formatString: 0
		lineageTag: 1d34bcf1-9175-4d43-95a8-2cab1de716a6
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column conversion_rate
		dataType: double
		lineageTag: f05afe39-5e5b-4f7a-98d2-d43043b778b5
		summarizeBy: none
		sourceColumn: conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition device_analysis = m
		mode: import
		source =
				let
				    源 = Csv.Document(File.Contents("D:\D30360\Documents\ecommerce_funnel_analysis\powerbi\data\device_analysis.csv"),[Delimiter=",", Columns=4, Encoding=936, QuoteStyle=QuoteStyle.None]),
				    提升的标题 = Table.PromoteHeaders(源, [PromoteAllScalars=true]),
				    更改的类型 = Table.TransformColumnTypes(提升的标题,{{"DeviceType", type text}, {"sessions", Int64.Type}, {"converted", Int64.Type}, {"conversion_rate", type number}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

